# 项目
app:
  id: company-official-website-server
  name: company-official-website-server
  author: nealxavier
  email: nealxavier@163.com
  github: https://github.com/NealXavier/company_official_website_server
  description: company-official-website-server
  version: 1.0.4


  # 读取指定环境
spring:
  profiles:
    active: prod # dev 或者 'prod'，根据您需要的环境
    




